// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC8sZg2wuxtNNz1eK7Z9_v2BEO81PjSDU',
    appId: '1:127075536500:web:5aa7427e1563f5e7e4cb21',
    messagingSenderId: '127075536500',
    projectId: 'database-sekolah-1-eef52',
    authDomain: 'database-sekolah-1-eef52.firebaseapp.com',
    storageBucket: 'database-sekolah-1-eef52.appspot.com',
    measurementId: 'G-PD25W5QL3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1OBZRqwDmaPppMeRo4ZR-oWth_q2qny0',
    appId: '1:127075536500:android:8f973aadf4e82f4be4cb21',
    messagingSenderId: '127075536500',
    projectId: 'database-sekolah-1-eef52',
    storageBucket: 'database-sekolah-1-eef52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM-fnwm3EfXLaKxvn9TgRRmtMnNc-ME_Q',
    appId: '1:127075536500:ios:4add7637b1adb28ae4cb21',
    messagingSenderId: '127075536500',
    projectId: 'database-sekolah-1-eef52',
    storageBucket: 'database-sekolah-1-eef52.appspot.com',
    iosBundleId: 'co.id.kenarok.sistemInformasiSekolah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM-fnwm3EfXLaKxvn9TgRRmtMnNc-ME_Q',
    appId: '1:127075536500:ios:4add7637b1adb28ae4cb21',
    messagingSenderId: '127075536500',
    projectId: 'database-sekolah-1-eef52',
    storageBucket: 'database-sekolah-1-eef52.appspot.com',
    iosBundleId: 'co.id.kenarok.sistemInformasiSekolah',
  );
}
